networks:
  kaspersky-symphony:

services:
  backend:
    container_name: backend
    build:
      context: ./
    env_file:
      - .env
    ports:
      - 4000:4000
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:prod"
    depends_on:
      - postgres
    restart: always
    networks:
      - kaspersky-symphony

  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - kaspersky-symphony
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kaspersky']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
